import React, { useState } from "react";
import { Newspaper, ArrowUpRight } from "lucide-react";

const POSTS = [
  { title: "Scaling a Multi-Agent SaaS to $100k MRR", tag: "Strategy", excerpt: "How Alexanda Martinz Inc. orchestrates CrewAI agents for autonomous growth." },
  { title: "Holas Defender v3.0: Threat Hunting at the Edge", tag: "Security", excerpt: "Anomaly matrices, NLP threat indices, and sovereign cloud defense." },
  { title: "Building a Cloud Industrial Park in 2026", tag: "Engineering", excerpt: "Supabase Realtime + FastAPI + React for parallel service portals." },
  { title: "Grok's Playbook for Viral SaaS Launches", tag: "Marketing", excerpt: "Retail vs wholesale pricing and organic acquisition loops." },
];

export default function BlogHub() {
  const [expanded, setExpanded] = useState<string | null>(null);

  return (
    <div className="space-y-6">
      <h1 className="text-lg font-semibold text-slate-100">Blog Hub — General & Tech</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {POSTS.map((p) => (
          <div key={p.title} className="card p-5">
            <div className="text-[9px] font-mono uppercase text-emerald-400 mb-2">{p.tag}</div>
            <div className="flex items-start justify-between gap-3">
              <h3 className="text-sm font-semibold text-slate-100">{p.title}</h3>
              <Newspaper className="w-4 h-4 text-slate-500 shrink-0" />
            </div>
            <p className="text-xs text-slate-400 mt-2">{p.excerpt}</p>
            <button onClick={() => setExpanded(expanded === p.title ? null : p.title)} className="mt-3 text-[11px] flex items-center gap-1 text-emerald-400 hover:underline">
              {expanded === p.title ? "Close" : "Read more"} <ArrowUpRight className="w-3 h-3" />
            </button>
            {expanded === p.title && (
              <div className="mt-3 text-xs text-slate-300 bg-ink border border-edge rounded-lg p-3">
                Full article content (mock) — {p.excerpt} This post is generated by the content pipeline and published to the Blog Hub portal.
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
